version: "3.0"
services:
  ros2:
    image: ros2_in_docker/humble:${CONTAINER_NAME:-humble}
    user: ${USER_NAME:-user}
    network_mode: "host"
    environment:
      - DISPLAY=$DISPLAY
      - PULSE_SERVER=$PULSE_SERVER
      - ROS_DOMAIN_ID=42
    volumes:
      - .:/home/user/colcon_ws
      - ${ROS_BAGS:-/dev/tmp}:/home/user/colcon_ws/bags/:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/user/1000/gdm/Xauthority:/home/user/.Xauthority
      - /run/user/1000/at-spi:/run/user/1000/at-spi
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      # for running with wsl on windows only
      - /mnt/wslg/:/mnt/wslg/