name: humble
root: ~/ros2_ws/
startup_window: ros2
tmux_command: tmux -2
windows:
  - ros2:
      layout: even-horizontal
      panes:
        - echo "\nAvailable local packages:" && ros2 pkg list
  - monitor:
      panes:
        - htop